version: '3.6'
services:
  homebridge:
    build:
      context: .
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Stockholm
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./homebridge:/homebridge
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
